# Generated by Django 5.0.4 on 2024-04-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='code_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='code_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
