# Generated by Django 5.0.4 on 2024-04-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'kutilmoqda'), (2, 'bekor qilish')], default=1),
        ),
    ]
